INTERVALS = {
  '1m' => 1,
  '3m' => 3,
  '5m' => 5,
  '15m' => 15,
  '30m' => 30,
  '1h' => 60,
  '2h' => 120,
  '4h' => 240,
  '6h' => 360,
  '8h' => 480,
  '12h' => 720,
  '1d' => 1440,
  '3d' => 4320,
  '1w' => 10_080,
  '1M' => 40_320
}.freeze

BINANCE_COINS = [
  "ETH",
  "LTC",
  "BNB",
  "NEO",
  "BCC",
  "GAS",
  "HSR",
  "MCO",
  "WTC",
  "LRC",
  "QTUM",
  "YOYO",
  "OMG",
  "ZRX",
  "STRAT",
  "SNGLS",
  "BQX",
  "KNC",
  "FUN",
  "SNM",
  "IOTA",
  "LINK",
  "XVG",
  "CTR",
  "SALT",
  "MDA",
  "MTL",
  "SUB",
  "EOS",
  "SNT",
  "ETC",
  "MTH",
  "ENG", "DNT", "ZEC", "BNT", "AST", "DASH", "OAX", "ICN", "BTG", "EVX", "REQ", "VIB", "TRX", "POWR", "ARK", "XRP", "MOD", "ENJ", "STORJ", "VEN",
  "KMD", "RCN", "NULS", "RDN", "XMR", "DLT", "AMB", "BAT", "BCPT", "ARN", "GVT", "CDT", "GXS", "POE", "QSP", "BTS", "XZC", "LSK", "TNT", "FUEL",
  "MANA", "BCD", "DGD", "ADX", "ADA", "PPT", "CMT", "XLM", "CND", "LEND", "WABI", "TNB", "WAVES", "GTO", "ICX", "OST", "ELF", "AION", "NEBL", "BRD", "EDO", "WINGS", "NAV", "LUN", "TRIG", "APPC", "VIBE", "RLC", "INS", "PIVX", "IOST", "CHAT", "STEEM", "NANO", "VIA", "BLZ", "AE", "RPX", "NCASH", "POA", "ZIL", "ONT", "STORM"]
