:concurrency: 10
# staging:
#   :concurrency: 10
production:
  :concurrency: 5
:queues:
  - critical
  - default
  - low
:schedule:
  jobs:
    every: '1m'
    class: CronWorker
  daily_jobs:
    every: '6h'
    class: DailyJobs
